settime: Sync from ipfire core203
commit dfe971738eb268e05359ce014f99640fb7cbe9ce
Author: Michael Tremer <michael.tremer@ipfire.org>
Date:   Wed May 27 14:49:01 2026 +0100

    settime: Remove braindead localization and subnet guessing

    This is so broken. OMG.

    There is no point to guess where the time servers are. The sync should
    happen regardless. The NTP daemon will also try to sync the time now and
    therefore we should rather fire and forget.

    Signed-off-by: Michael Tremer <michael.tremer@ipfire.org>

commit cffd2c3978e513f64a2549b14d1e08abf83ef6cc
Author: Michael Tremer <michael.tremer@ipfire.org>
Date:   Wed May 27 14:40:02 2026 +0100

    settime: Return exit code from ntpdate

    Signed-off-by: Michael Tremer <michael.tremer@ipfire.org>

Signed-off-by: Vincent Li <vincent.mc.li@gmail.com>

diff --git a/src/scripts/settime b/src/scripts/settime
--- a/src/scripts/settime
+++ b/src/scripts/settime
@@ -19,58 +19,24 @@
 #                                                                             #
 ###############################################################################
 
-ongreen=1
-green=$(cat /var/ipfire/ethernet/settings | grep GREEN_NETADDRESS)
-if [ -z "$green" ]; then
-	:		# no Green subnet
-else
-	green=${green##*=}; green="${green%.*}.[0-9]"
-	if [ -n "$(cat /var/ipfire/time/settime.conf | grep $green)" ]; then
-		ongreen=0	# NTP on Green
-	fi
-fi
-
-onorange=1
-orange=$(cat /var/ipfire/ethernet/settings | grep ORANGE_NETADDRESS)
-if [ -z "$orange" ]; then
-	:		# no Orange subnet
-else
-	orange=${orange##*=}; orange="${orange%.*}.[0-9]"
-	if [ -n "$(cat /var/ipfire/time/settime.conf | grep $orange)" ]; then
-		onorange=0	# NTP on Orange
-	fi
-fi
-
-# find out language
-tlanguage=$(cat /var/ipfire/main/settings | grep LANGUAGE)
-tlanguage=${tlanguage##*=}
-
 if [ -n "$1" ]; then
-	if [ -e /var/ipfire/red/active ] || [ "$ongreen" -eq 0 ] || [ "$onorange" -eq 0 ]; then
-		/usr/bin/ntpdate -su $1 $2
-		ntpdatetest=$?
+	/usr/bin/ntpdate -su $1 $2
+	ntpdatetest=$?
 
-		if [ "$ntpdatetest" -eq 0 ]; then
-			case $tlanguage in
-				en ) date "+%X %Z on %d %B %Y" > /var/lock/time/lastset ;
-					logger -t ipfire "NTP synchronisation event" ;;
-				de ) date "+%X Uhr am %d.%m.%Y" > /var/lock/time/lastset ;
-					logger -t ipfire "NTP Synchronisierung" ;;
-				*  ) date "+%X %Z, %Y-%m-%d" > /var/lock/time/lastset ;
-					logger -t ipfire "NTP synchronisation" ;;
-			esac
+	if [ "$ntpdatetest" -eq 0 ]; then
+		date "+%X %Z, %Y-%m-%d" > /var/lock/time/lastset
 
-			/sbin/hwclock --systohc
-			rm -f /var/lock/time/settimenow
-			# reset counter variable
-			cp /var/ipfire/time/counter.conf /var/lock/time/counter
-		else
-			case $tlanguage in
-				de ) logger -t ipfire "ntpdate fehlerhaft" ;;
-				*  ) logger -t ipfire "ntpdate error" ;;
-			esac
-		fi
+		/sbin/hwclock --systohc
+		rm -f /var/lock/time/settimenow
+		# reset counter variable
+		cp /var/ipfire/time/counter.conf /var/lock/time/counter
+	else
+		logger -t ipfire "ntpdate error"
 	fi
+
+	exit ${ntpdatetest}
 else
 	echo Missing parameter
 fi
+
+exit 0
